// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6F3rCFVl5LV0e-_cLqGJOa4XjUOW0CyA',
    appId: '1:665235210465:web:a918f89441aa67c43f77a0',
    messagingSenderId: '665235210465',
    projectId: 'londoncyclee',
    authDomain: 'londoncyclee.firebaseapp.com',
    storageBucket: 'londoncyclee.appspot.com',
    measurementId: 'G-LV89T5RPPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlWCgFmSe2c1GFyuafje8xdhHQY144hns',
    appId: '1:665235210465:android:dc80099d176677443f77a0',
    messagingSenderId: '665235210465',
    projectId: 'londoncyclee',
    storageBucket: 'londoncyclee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApryzTKCbb-9EQKqFsK7HuGzxz1SFf-OI',
    appId: '1:665235210465:ios:42bc22c6f19cdf8a3f77a0',
    messagingSenderId: '665235210465',
    projectId: 'londoncyclee',
    storageBucket: 'londoncyclee.appspot.com',
    iosClientId: '665235210465-sa1io1hi1112b222qp5d41t1rjp290dp.apps.googleusercontent.com',
    iosBundleId: 'com.example.bikeTourApp',
  );
}
